# Generated by Django 4.2.7 on 2023-11-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_joueur_remove_equipement_photo_delete_character_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joueur',
            name='nom',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
