# Generated by Django 4.2.7 on 2023-11-14 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_joueur_etat_remove_joueur_lieu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joueur',
            name='etat',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joueur',
            name='lieu',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.equipement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joueur',
            name='nom',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joueur',
            name='photo',
            field=models.ImageField(default=0, upload_to='photos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joueur',
            name='poste',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joueur',
            name='taille',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
