# Generated by Django 4.2.7 on 2023-11-14 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_joueur_etat_joueur_lieu_joueur_nom_joueur_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joueur',
            name='poste',
        ),
        migrations.RemoveField(
            model_name='joueur',
            name='taille',
        ),
    ]
