# Generated by Django 4.2.7 on 2023-11-14 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_joueur_poste_remove_joueur_taille'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joueur',
            old_name='etat',
            new_name='poste',
        ),
    ]
