# Generated by Django 4.2.7 on 2023-11-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_etat_joueur_poste'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='placemax',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
